services:
  # 'web' es el nombre que le damos a nuestro servicio (puedes ponerle 'app' si quieres)
  app:
    # Le decimos que construya la imagen usando el Dockerfile de la carpeta actual
    build: .

    # Nombre que tendrá el contenedor cuando esté encendido
    container_name: peterparts-web

    # Mapeo de puertos: "PUERTO_PC : PUERTO_CONTENEDOR"
    ports:
      - "8080:80"

    # Sincronización de archivos (ESTO ES MAGIA)
    volumes:
      - .:/var/www/html
